### ISSUE TITLE
GetRealTimeQuotesAsync => Requested Information Not Available On Yahoo Finance

### ISSUE THREAD

**Issue by stagnoman** [ooples/OoplesFinance.YahooFinanceAPI#15]
Hi there, 

I was looking for live data. I tried GetRealTimeQuotesAsync but it returns me the following error:

-------------------------------------------------------
var symbol = "TSLA";
var yahooClient = new YahooClient();
var r = await yahooClient.GetRealTimeQuotesAsync(symbol);
Console.WriteLine($"{r.Symbol} {r.RegularMarketPrice} {r.Bid} {r.BidSize} {r.Ask} {r.AskSize}");
-------------------------------------------------------
Error: 
System.InvalidOperationException: 'Requested Information Not Available On Yahoo Finance'

Would you pls help me this? 
Thks

**Comment by ooples** [comment]
@stagnoman At first glance it looks like Yahoo changed the URL again so I'm looking into this further. Will let you know when I have an update

**Comment by ooples** [comment]
@stagnoman Looks like it has been taken down for now due to a decision from Yahoo but will update you if they decide to add it again. I will also try to find a workaround

**Comment by tjitra** [comment]
I got this error to on Debian, use net 7.0
