### ISSUE TITLE
Error code line 16

### ISSUE THREAD

**Issue by Lilxxchrisxx** [ooples/OoplesFinance.YahooFinanceAPI#19]
It shows an error in line 16 of the code that you provide and it says this"JSON integer 15728700416 is too large or small for an Int32. Path 'quoteSummary.result[0].defaultKeyStatistics.impliedSharesOutstanding.raw', line 1, position 1063.", already send you and email and I would really appriciate if you find a way to fix it thank you

**Comment by ooples** [comment]
@Lilxxchrisxx Just did an update and new version on nuget is 1.5 which will fix this error for you. Please get the latest version and confirm that the issue is resolved.

**Comment by Lilxxchrisxx** [comment]
so I try and now when I try running it just open the terminal and it closes it 
<img width="1280" alt="Screen Shot 2023-06-29 at 2 10 55 AM" src="https://github.com/ooples/OoplesFinance.YahooFinanceAPI/assets/137856345/fa02053d-cadf-466d-85b2-be2d03eec41f"> 
I don't know if is just me doing something wrong or what and thank you for your help.

**Comment by ooples** [comment]
According to your screenshot, you have the unit test project set as your
start up project. If you want to use this library in your existing project
then you would want to install it via nuget package but if you just want to
run this for testing then make sure the TestConsoleApp is set as your start
up project

Franklin

**Comment by Lilxxchrisxx** [comment]
alright, now it shows anothe error it says this "System.InvalidOperationException has been thrown'' its for line 49 and thank you a lot for the help

**Comment by ooples** [comment]
What is the message for that exception?

**Comment by Lilxxchrisxx** [comment]
it just says this "Requested Information Not Available On Yahoo Finance"

**Comment by ooples** [comment]
Yeah that means what it says. What symbol are you trying to use? Which
method are you using?

**Comment by Lilxxchrisxx** [comment]
I trying to use the same code you have, You can look at it in one of the comments that as the screenshot

**Comment by ooples** [comment]
@Lilxxchrisxx  line 49 is this: 

//var chartInfoList = await yahooClient.GetChartInfoAsync("GOOG", TimeRange._1Year, TimeInterval._1Day);

When I uncomment it, it works just fine without errors so can you please give me more info so I can replicate what you are doing?
