### ISSUE TITLE
Question: Is there a way to retrieve the name of the company via the symbol?

### ISSUE THREAD

**Issue by Codepoet77** [ooples/OoplesFinance.YahooFinanceAPI#80]
Is there a way to retrieve the name of the company via the symbol (e.g. symbol DIS would return Disney, AAPL would return Apple inc, etc)? At first glance I did not see a way to do this.

**Comment by ooples** [comment]
@Codepoet77 As far as I'm aware, there is no specific Yahoo Finance API call that gets the company name which is a bit odd so my assumption is that I just haven't run across it yet. If you can find anymore info about how to get this with their latest API, then I would be happy to add it to this library
