### ISSUE TITLE
Why don't I get daily prices?

### ISSUE THREAD

**Issue by MozgC** [ooples/OoplesFinance.YahooFinanceAPI#83]
Hi, just trying your library for the first time and I don't get daily prices, I tried a few different tickers.

`var chartInfoList2 = await yahooClient.GetChartInfoAsync("VOO", TimeRange.Max, TimeInterval._1Day);`

![image](https://github.com/ooples/OoplesFinance.YahooFinanceAPI/assets/678703/e1248268-22dc-4e65-91c5-39cd3c7961c3)

You can see I'm only getting monthly prices.

Here YF does have daily prices:
https://finance.yahoo.com/quote/VOO/history?period1=1283990400&period2=1716768000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true

**Comment by ooples** [comment]
@MozgC This seems to be a very strange issue with the TimeRange.Max in particular. You can see from my screenshot below that I'm using the 5 year range and I can see the daily values correctly. I also confirmed the max time range directly using Yahoo Finance and I can see that for some reason, the 1 day interval returns the monthly values so this definitely is coming from the Yahoo side of things.

![image](https://github.com/ooples/OoplesFinance.YahooFinanceAPI/assets/3075685/f461eaa9-8fda-48e0-90af-2746f82a37ea)

**Comment by MozgC** [comment]
@ooples thank you. I guess I will use 10years then.
