### ISSUE TITLE
Faild to get Cumb

### ISSUE THREAD

**Issue by algo0749** [ooples/OoplesFinance.YahooFinanceAPI#90]
From Friday night it doesn't work when I want to get the close price from Yahoo.

Error obteniendo los precios diarios en Yahoo del instrumento :FER.MC, error: Failed to get crumb
Error calculando los pivots semanales Sequence contains no elements
Error obteniendo los precios diarios en Yahoo del instrumento :AENA.MC, error: Failed to get crumb
Error calculando los pivots semanales Sequence contains no elements
Error obteniendo los precios diarios en Yahoo del instrumento :IBE.MC, error: Failed to get crumb
Error calculando los pivots semanales Sequence contains no elements
Error obteniendo los precios diarios en Yahoo del instrumento :MRL.MC, error: Failed to get crumb

**Comment by algo0749** [comment]
I have try to connect with VPN from USA and I have the same error.

Thnaks

**Comment by ooples** [comment]
@algo0749  Can you please include more details for your issues such as the code you are using so I can help you look into this? Also please try the new version 1.6.5 that fixes similar issues for certain yahoo methods which might fix your issue

**Comment by algo0749** [comment]
Thank you for your help. 

From what I see, it's Yahoo that has changed its policies and that's why it has stopped working. In Europe, having to accept a cookie every time you access a new website is a nuisance.

It has now been solved with your new version.

Thanks again.

**Comment by ooples** [comment]
No problem and glad it is working for you
